## Class Exercise 5


### 1.	Import NumPy in Jupyter notebook.
- a.	Generate a 1D NumPy array of 10 random integers between 1 and 100.



In [1]:
import numpy as np

# Generate a 1D NumPy array of 10 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

print(random_array)


[61 42 61 87 88 98 53 92 55 88]


- b.	Access and print the first and last elements of the array.

In [3]:
import numpy as np

# Generate a 1D NumPy array of 10 random integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

# Access and print the first element of the array
print("First element:", random_array[0])

# Access and print the last element of the array
print("Last element:", random_array[-1])


First element: 45
Last element: 52


- c.	Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers.


In [4]:
import numpy as np

# Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers
random_float_array = np.random.rand(3, 3)

print(random_float_array)


[[0.84674919 0.85484451 0.36387604]
 [0.59827681 0.12430476 0.1350183 ]
 [0.82167308 0.43609183 0.01486285]]


### 2.	Use the 2D array generated in Exercise 1 c. Practice slicing arrays to access sub-arrays.

- a.	Print the first row of the 2D array.


In [5]:
import numpy as np

# The variable "random_float_array" is the 2D array generated in Exercise 1

# Print the first row of the 2D array
print("First row of the 2D array:")
print(random_float_array[0])


First row of the 2D array:
[0.84674919 0.85484451 0.36387604]


- b.	Print the last column of the 2D array.

In [10]:
# Print the last column of the 2D array
print("The last column of the 2D array:")
print(random_float_array[:,-1])

The last column of the 2D array:
[0.36387604 0.1350183  0.01486285]


- c.	Create and print a sub-array consisting of the first two rows and first two columns.

In [11]:
# Create and print the sub-array consisting of the first two rows and first two columns
sub_array = random_float_array[:2, :2]

print("Sub-array consisting of the first two rows and first two columns:")
print(sub_array)

Sub-array consisting of the first two rows and first two columns:
[[0.84674919 0.85484451]
 [0.59827681 0.12430476]]


## 3.	Generate two 1D NumPy arrays of 5 random integers each. 

- a.	Add the two arrays and print the result.

In [12]:
# Generate two 1D NumPy arrays of 5 random integers each
array1 = np.random.randint(1, 100, size=5)
array2 = np.random.randint(1, 100, size=5)

print("Array 1:", array1)
print("Array 2:", array2)

# a. Add the two arrays and print the result
result_addition = array1 + array2
print("Addition Result:", result_addition)

Array 1: [67 89 28 50 45]
Array 2: [96 51 28 49 95]
Addition Result: [163 140  56  99 140]


- b. Multiply the two arrays (element-wise) and print the result

In [13]:
# Multiply the two arrays (element-wise) and print the result
result_multiplication = array1 * array2
print("Multiplication Result:", result_multiplication)


Multiplication Result: [6432 4539  784 2450 4275]


- c. Calculate the square of every element in the first array and print it

In [14]:
# Calculate the square of every element in the first array and print it
result_square = array1 ** 2
print("Square of Array 1:", result_square)

Square of Array 1: [4489 7921  784 2500 2025]


## 4.	Generate two 2D NumPy arrays, A of shape (2, 3) and B of shape (3, 2), with random integers.

- a.	Perform matrix multiplication between A and B (using np.dot() or the @ operator) and print the result.

In [15]:
# Generate two 2D NumPy arrays A of shape (2, 3) and B of shape (3, 2) with random integers
A = np.random.randint(1, 10, size=(2, 3))
B = np.random.randint(1, 10, size=(3, 2))

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# a. Perform matrix multiplication between A and B and print the result
result_matrix_multiplication = np.dot(A, B)
# Or One can also use the @ operator for matrix multiplication
# result_matrix_multiplication = A @ B
print("\nResult of matrix multiplication between A and B:")
print(result_matrix_multiplication)


Matrix A:
[[1 2 1]
 [4 3 7]]

Matrix B:
[[3 5]
 [2 3]
 [7 9]]

Result of matrix multiplication between A and B:
[[14 20]
 [67 92]]


- b.	Can A and B perform element-wise multiplication using *, why?

###### No, A and B cannot perform element-wise multiplication using * because they do not have compatible shapes.
In order to perform element-wise multiplication, the arrays must have the same shape or one of them must be broadcastable to the other.
A is of shape (2, 3) and B is of shape (3, 2), so their shapes are not compatible for element-wise multiplication.
Element-wise multiplication would require both arrays to have the same shape or one of them to be broadcastable to the other.